# Generated by Django 2.2.11 on 2020-03-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_emri', models.CharField(max_length=100)),
                ('tup_sayisi', models.CharField(max_length=100)),
                ('baslangic', models.CharField(max_length=100)),
                ('bitis', models.CharField(max_length=100)),
                ('emri_veren', models.CharField(max_length=100)),
                ('zaman', models.CharField(max_length=100)),
            ],
        ),
    ]
