# Generated by Django 2.2.11 on 2020-03-18 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_emir'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emir',
            name='zaman',
        ),
    ]
