# Generated by Django 2.2.11 on 2020-03-20 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_emir_zaman'),
    ]

    operations = [
        migrations.AddField(
            model_name='emir',
            name='emir_zamani',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
