# Generated by Django 2.2.11 on 2020-03-20 20:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200320_2339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emir',
            name='baslangic',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 20, 40, 48, 756901, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emir',
            name='bitis',
            field=models.DateField(default=datetime.datetime(2020, 3, 20, 20, 40, 48, 756933, tzinfo=utc)),
        ),
    ]
