# Generated by Django 2.2.11 on 2020-03-21 07:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200320_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='emir',
            name='urun_kodu',
            field=models.CharField(default=1111111, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emir',
            name='baslangic',
            field=models.DateField(default=datetime.datetime(2020, 3, 21, 7, 50, 59, 688157, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emir',
            name='bitis',
            field=models.DateField(default=datetime.datetime(2020, 3, 21, 7, 50, 59, 688190, tzinfo=utc)),
        ),
    ]
