# Generated by Django 2.2.11 on 2020-03-22 08:58

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_auto_20200321_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tur', models.CharField(max_length=30)),
                ('seri_no', models.CharField(max_length=20)),
                ('acma', models.CharField(max_length=20)),
                ('kapatma', models.CharField(max_length=20)),
                ('test_tarihi', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='emir',
            name='baslangic',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 8, 58, 29, 384776, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emir',
            name='bitis',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 8, 58, 29, 384825, tzinfo=utc)),
        ),
    ]
