# Generated by Django 2.2.11 on 2020-03-22 09:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20200322_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emir',
            name='baslangic',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 9, 31, 35, 720387, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emir',
            name='bitis',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 9, 31, 35, 720432, tzinfo=utc)),
        ),
    ]
