# Generated by Django 2.2.11 on 2020-03-22 10:37

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_auto_20200322_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='testi_yapan',
            field=models.CharField(default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emir',
            name='baslangic',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 10, 37, 40, 497512, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='emir',
            name='bitis',
            field=models.DateField(default=datetime.datetime(2020, 3, 22, 10, 37, 40, 497543, tzinfo=utc)),
        ),
    ]
